server:
  port: 8080

spring:
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://ep-ancient-bread-ami7c8mk-pooler.c-5.us-east-1.aws.neon.tech/generador}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_zm5bPdG9ujoC}
    properties:
      sslMode: require
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config

rapidapi:
  key: ${RAPIDAPI_KEY:6c24a42bdemsh8ee142e9f2ececbp16d671jsndc3e60c45d52}
  tts:
    host: ${RAPIDAPI_TTS_HOST:open-ai-text-to-speech1.p.rapidapi.com}
    url: ${RAPIDAPI_TTS_URL:https://open-ai-text-to-speech1.p.rapidapi.com/}
  email:
    host: ${RAPIDAPI_EMAIL_HOST:validect-email-verification-v1.p.rapidapi.com}
    url: ${RAPIDAPI_EMAIL_URL:https://validect-email-verification-v1.p.rapidapi.com/v1/verify}
