apiVersion: v1
kind: Service
metadata:
  name: salvador-quispe-29-service
  namespace: salvador-quispe-29
spec:
  selector:
    app: salvador-quispe-29-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
