apiVersion: v1
kind: Secret
metadata:
  name: salvador-quispe-29-secret
  namespace: salvador-quispe-29
type: Opaque
stringData:
  DB_URL: "r2dbc:postgresql://ep-ancient-bread-ami7c8mk-pooler.c-5.us-east-1.aws.neon.tech/generador"
  DB_USERNAME: "neondb_owner"
  DB_PASSWORD: "npg_zm5bPdG9ujoC"
  RAPIDAPI_KEY: "6c24a42bdemsh8ee142e9f2ececbp16d671jsndc3e60c45d52"
  RAPIDAPI_TTS_HOST: "open-ai-text-to-speech1.p.rapidapi.com"
  RAPIDAPI_TTS_URL: "https://open-ai-text-to-speech1.p.rapidapi.com/"
  RAPIDAPI_EMAIL_HOST: "validect-email-verification-v1.p.rapidapi.com"
  RAPIDAPI_EMAIL_URL: "https://validect-email-verification-v1.p.rapidapi.com/v1/verify"
