name: Backend CI DockerHub

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/as241s5_aej_29-be .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/as241s5_aej_29-be